function symThet = T(x)
%T
%    symThet = T(X)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-May-2025 00:42:02

symThet = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;x;-x.*(x.*(1.0e+1./1.47e+2)-1.0);x.*((x.*(1.0e+1./1.47e+2)-1.0).*(x.*(2.0e+1./1.47e+2)-2.0)-1.0);-x.*(x.*(-1.0e+1./1.47e+2)+((x.*(1.0e+1./1.47e+2)-1.0).*(x.*(2.0e+1./1.47e+2)-2.0)-1.0).*(x.*(2.0e+1./1.47e+2)-2.0)+1.0)];
