function [delta_LE, delta_TE, beta_y, beta_x] = G1_2(obj, ang, varargin)
 
% arguments
%     obj analysisBase
%     ang=0;
% end
% arguments (Repeating)
%     varargin
% end

%% fixed parameters...fprcing parts for the added weight

s_I = 0.025; %measurment location for WRBM
s_II = 0.050;
dy1 = 0.075; 
dy2 = -0.075;
opts = optimoptions('fsolve', 'Display', 'off');

% function handle for external load
mass = 132/1000;
hOfst = 29/1000;
vOfst = -9.05/1000;
dc = -0.075*0.6667;

dw = obj.transF'*project.basis.W(0.6225);
dv = obj.transF'*project.basis.V(0.6225);
dt = obj.transF'*project.basis.T(0.6225);
dw1 = obj.transF'*project.basis.W1(0.6225);
dv1 = obj.transF'*project.basis.V1(0.6225);

df_xy = @(q,ang)(mass*[zeros(size(obj.transF,2), 1);...
    -9.81*cos(ang)*(-vOfst*dt*(dt'*q(obj.structDisp))+...
    -vOfst*dw1*(dw1'*q(obj.structDisp))+...
    hOfst*dw1)+...
    -9.81*sin(ang)*(-dt*vOfst-vOfst*dw1*(dv1'*q(obj.structDisp))+...
    -vOfst*dv1*(dw1'*q(obj.structDisp))+...
    hOfst*dv1)]);

df0 = @(q,ang)(mass*9.81*[zeros(size(obj.transF,2), 1);...
    -sin(ang)*dv - cos(ang)*dw]);

dx = @(q,ang)(mass*9.81*[zeros(size(obj.transF,2), 1);...
    -sin(ang)*dc*(-dt*(dt'*q(obj.structDisp))+...
    -dv1*(dv1'*q(obj.structDisp))+...
    -dw1*(q(obj.structDisp)'*dt.*dv1'*q(obj.structDisp))+...
    -dv1*(q(obj.structDisp)'*dt.*dw1'*q(obj.structDisp))+...
    -dt*(q(obj.structDisp)'*dw1.*dv1'*q(obj.structDisp)))+...
    -cos(ang)*dc*(dt*(1 - 0.5*q(obj.structDisp)'*dw1.*dw1'*q(obj.structDisp))+...
    -dw1*(q(obj.structDisp)'*dw1.*dt'*q(obj.structDisp))+...
    -0.5*dt*(q(obj.structDisp)'*dt.*dt'*q(obj.structDisp)))]);

%% unloaded alp=0 case for displacement offsets....

alp=0*pi/180;
q=obj.q0_struct;
q = fsolve(@(q_all)(...
    obj.structDeriv(q_all,'alpha0', alp, varargin{:})), q, opts);

[x,y,z] = obj.getDisplField(q, obj.geom.L,'beamModel');

delta_LE0 = z(1)*cos(alp) + y(1)*sin(alp) +...
    -dy1*sin(alp);

delta_TE0 = z(2)*cos(alp) + y(2)*sin(alp) +...
    -dy2*sin(alp);

%% solve for alpha=0 case for load offsets..

obj.externalForce = @(q)(df_xy(q, 0) +...
    df0(q, 0) +...
    dx(q,0)); %add external force...

q=obj.q0_struct;
q = fsolve(@(q_all)(...
    obj.structDeriv(q_all,'alpha0', 0, varargin{:})), q, opts);

%record wing root bending moments....
beta_y0 = project.basis.W2(s_I)'*obj.transF*q(obj.structDisp);
beta_x0 = project.basis.T1(s_II)'*obj.transF*q(obj.structDisp);

%% solve through angle vector...

for a_idx=1:length(ang)

    alp = ang(a_idx);

    obj.externalForce = @(q)(df_xy(q, alp) +...
                            df0(q, alp) +...
                            dx(q,alp)); %add external force...

    if isempty(varargin)
        q = fsolve(@(q_all)(...
            obj.structDeriv(q_all,'alpha0', alp)),...
            q, opts);
    else
        q = fsolve(@(q_all)(...
            obj.structDeriv(q_all,'alpha0', alp,...
            varargin{:})),...
            q, opts);
    end

    [x,y,z] = obj.getDisplField(q, obj.geom.L,'beamModel');

    delta_LE(1,a_idx) = z(1)*cos(alp) + y(1)*sin(alp) +...
         -dy1*sin(alp) - delta_LE0;

    delta_TE(1,a_idx) = z(2)*cos(alp) + y(2)*sin(alp) +...
        -dy2*sin(alp) - delta_TE0;

    %record wing root bending moments....
    beta_y(1,a_idx) = project.basis.W2(s_I)'*obj.transF*q(obj.structDisp)...
        - beta_y0;
    beta_x(1,a_idx) = project.basis.T1(s_II)'*obj.transF*q(obj.structDisp)...
        - beta_x0;
end

clear obj.externalForce

end