function symV = V(x)
%V
%    symV = V(X)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Jun-2025 11:57:52

symV = [0.0;0.0;0.0;0.0;0.0;0.0;x.^2;-x.^2.*(x.*1.076402929490188e-1-1.0);0.0;0.0;0.0;0.0];
